<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) );

require_once( "includes/DefaultSettings.php" );

$wgGroupPermissions = array();
 
// Implicit group for all visitors
        $wgGroupPermissions['*'    ]['createaccount']   = false;         // 1.5.0
        $wgGroupPermissions['*'    ]['read']            = true;         // 1.5.0
        $wgGroupPermissions['*'    ]['edit']            = false;         // 1.5.0
        $wgGroupPermissions['*'    ]['createpage']      = false;         // 1.6.0
        $wgGroupPermissions['*'    ]['createtalk']      = false;         // 1.6.0
 
// Implicit group for all logged-in accounts
        $wgGroupPermissions['user' ]['move']            = true;         // 1.5.0
        $wgGroupPermissions['user' ]['read']            = true;         // 1.5.0
        $wgGroupPermissions['user' ]['edit']            = true;         // 1.5.0
        $wgGroupPermissions['user' ]['createpage']      = true;         // 1.6.0
        $wgGroupPermissions['user' ]['createtalk']      = true;         // 1.6.0
        $wgGroupPermissions['user' ]['upload']          = true;         // 1.5.0
        $wgGroupPermissions['user' ]['reupload']        = true;         // 1.6.0
        $wgGroupPermissions['user' ]['reupload-shared'] = true;         // 1.6.0
        $wgGroupPermissions['user' ]['minoredit']       = true;         // 1.6.0
 
// Implicit group for accounts that pass $wgAutoConfirmAge
        $wgGroupPermissions['autoconfirmed']['autoconfirmed'] = true;   // 1.6.0
 
// Implicit group for accounts with confirmed email addresses
// This has little use when email address confirmation is off
// This group has been removed by default in 1.13.0
        $wgGroupPermissions['emailconfirmed']['emailconfirmed'] = true; // 1.7.0
 
// Users with bot privilege can have their edits hidden
// from various log pages by default
        $wgGroupPermissions['bot'  ]['bot']             = true;         // 1.5.0
        $wgGroupPermissions['bot'  ]['autoconfirmed']   = true;         // 1.6.0
// Can edit all protected pages without cascade protection enabled
// Added in 1.13.0, but commented out in source
//      $wgGroupPermissions['bot'  ]['editprotected']   = true;         // 1.13.0
 
// Most extra permission abilities go to this group
        $wgGroupPermissions['sysop']['block']           = true;         // 1.5.0
        $wgGroupPermissions['sysop']['createaccount']   = true;         // 1.5.0
        $wgGroupPermissions['sysop']['delete']          = true;         // 1.5.0
        $wgGroupPermissions['sysop']['deletedhistory']  = true;         // 1.6.0
        $wgGroupPermissions['sysop']['editinterface']   = true;         // 1.5.0
        $wgGroupPermissions['sysop']['import']          = true;         // 1.5.0
        $wgGroupPermissions['sysop']['importupload']    = true;         // 1.5.0
        $wgGroupPermissions['sysop']['move']            = true;         // 1.5.0
        $wgGroupPermissions['sysop']['patrol']          = true;         // 1.5.0
        $wgGroupPermissions['sysop']['autopatrol']      = true;         // 1.9.0
        $wgGroupPermissions['sysop']['protect']         = true;         // 1.5.0
        $wgGroupPermissions['sysop']['proxyunbannable'] = true;         // 1.7.0
        $wgGroupPermissions['sysop']['rollback']        = true;         // 1.5.0
        $wgGroupPermissions['sysop']['trackback']       = true;         // 1.7.0
        $wgGroupPermissions['sysop']['upload']          = true;         // 1.5.0
        $wgGroupPermissions['sysop']['reupload']        = true;         // 1.6.0
        $wgGroupPermissions['sysop']['reupload-shared'] = true;         // 1.6.0
        $wgGroupPermissions['sysop']['unwatchedpages']  = true;         // 1.6.0
        $wgGroupPermissions['sysop']['autoconfirmed']   = true;         // 1.6.0
        $wgGroupPermissions['sysop']['upload_by_url']   = true;         // 1.8.0
        $wgGroupPermissions['sysop']['ipblock-exempt']  = true;         // 1.9.0
// Access to Special:MergeHistory. This was added in 1.12, but remains commented out in the source
//    $wgGroupPermissions['sysop']['mergehistory']    = true;         // 1.12.0
 
// Permission to change users' group assignments
        $wgGroupPermissions['bureaucrat']['userrights']  = true;        // 1.5.0
//      $wgGroupPermissions['bureaucrat']['noratelimit'] = true;        // 1.13.0
// Permission to change users' groups assignments across wikis
// Added in 1.12.0, but remain commented out in the source
//    $wgGroupPermissions['bureaucrat']['userrights-interwiki'] = true; // 1.12.0
 
 
// Experimental permissions, not ready for production use
// These were added in 1.6.0, but remain commented out in the source.
// This code was removed in 1.13.0, replaced instead by the next block
//    $wgGroupPermissions['sysop']['deleterevision'] = true;          // 1.6.0
//    $wgGroupPermissions['bureaucrat']['hiderevision'] = true;       // 1.6.0, removed in 1.13.0
 
// The following code was added in 1.13.0
//    $wgGroupPermissions['sysop']['deleterevision']  = true;         // 1.6.0
// To hide usernames from users and Sysops
// Added in 1.10.0, but not added into DefaultSettings.php until 1.13.0
//    $wgGroupPermissions['suppress']['hideuser'] = true;             // 1.10.0
// To hide revisions/log items from users and Sysops
// Replaces the 'hiderevision' right added in 1.6.0
//    $wgGroupPermissions['suppress']['suppressrevision'] = true;     // 1.13.0
// For private suppression log access
//    $wgGroupPermissions['suppress']['suppress'] = true;             // 1.13.0
 
// Used by the Special:Renameuser extension
// This setting was removed in 1.6.0 as the extension is not part of the default
// MediaWiki distribution.
        $wgGroupPermissions['bureaucrat']['renameuser'] = true;         // 1.5.0, removed in 1.6.0


# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
} elseif ( empty( $wgNoOutputBuffer ) ) {
	## Compress output if the browser supports it
	if( !ini_get( 'zlib.output_compression' ) ) @ob_start( 'ob_gzhandler' );
}

$wgSitename         = "DFW";

$wgScriptPath	    = "/dfwwiki";
$wgScript           = "$wgScriptPath/index.php";
$wgRedirectScript   = "$wgScriptPath/redirect.php";

## For more information on customizing the URLs please see:
## http://meta.wikimedia.org/wiki/Eliminating_index.php_from_the_url
## If using PHP as a CGI module, the ?title= style usually must be used.
# $wgArticlePath      = "$wgScript/$1";
# $wgArticlePath      = "$wgScript?title=$1";

$wgStylePath        = "$wgScriptPath/skins";
$wgStyleDirectory   = "$IP/skins";
$wgLogo             = "$wgStylePath/common/images/wallace-elegy.jpg";

$wgUploadPath       = "$wgScriptPath/images";
$wgUploadDirectory  = "$IP/images";

$wgEnableEmail = true;
$wgEnableUserEmail = true;

$wgEmergencyContact = "machines@machines.pomona.edu";
$wgPasswordSender	= "machines@machines.pomona.edu";

## For a detailed description of the following switches see
## http://meta.wikimedia.org/Enotif and http://meta.wikimedia.org/Eauthent
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

$wgDBserver         = "mysql.machines.plannedobsolescence.net";
$wgDBname           = "machines_dfwwiki";
$wgDBuser           = "mach_dfwwiki";
$wgDBpassword       = "a!thoa";
$wgDBprefix         = "";
$wgDBtype           = "mysql";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## Caching
$wgUseFileCache = true; /* default: false */
$wgFileCacheDirectory = "$IP/cache";
$wgShowIPinHeader = false;


## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads		= true;
$wgUseImageResize		= true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgFileExtensions = array('png', 'gif', 'jpg', 'jpeg', 'doc', 'xls', 'mpp', 'pdf', 'zip');

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX	         = false;
$wgMathPath         = "{$wgUploadPath}/math";
$wgMathDirectory    = "{$wgUploadDirectory}/math";
$wgTmpDirectory     = "{$wgUploadDirectory}/tmp";

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "12e7e6db72091f15b36389cebdae6a4849285ab6a0713247dc2a6529578cdc90";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'vector';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "http://creativecommons.org/licenses/by-sa/3.0/";
$wgRightsText = "Creative Commons Attribution Share Alike";
$wgRightsIcon = "{$wgStylePath}/common/images/cc-by-sa.png";

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$configdate = gmdate( 'YmdHis', @filemtime( __FILE__ ) );
$wgCacheEpoch = max( $wgCacheEpoch, $configdate );

?>